# Generated by Django 4.2.2 on 2023-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sexo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome completo'),
        ),
    ]
