# Generated by Django 4.2.2 on 2023-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_user_sexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_Teacher',
        ),
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, verbose_name='Altura'),
        ),
    ]
