# Generated by Django 4.2.2 on 2023-06-29 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_remove_user_is_teacher_alter_user_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Altura'),
        ),
    ]
