# Generated by Django 4.2.2 on 2023-06-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0003_alter_exercicios_do_treino_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicios',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='exercicios/imagens', verbose_name='imagem descritiva'),
        ),
    ]
