# Generated by Django 4.2.2 on 2023-07-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0004_exercicios_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicios',
            name='descanco',
            field=models.CharField(max_length=100, verbose_name='Tempo de descanço'),
        ),
    ]
